CC=g++
CFLAGS=-std=c++11 -Wall

chatTCP:
                $(CC) chatTCP.cpp $(CFLAGS) -o chatTCP -lpthread
chatsig:
                $(CC) chatsig.cpp $(CFLAGS) -o chatSIG -lpthread
chat:
                $(CC) chat.cpp $(CFLAGS) -o chat -lpthread

